### ISSUE TITLE
Implement marshaling and unmarshalling of Hll

### ISSUE THREAD

**Issue by drevell** [lytics/hll#5]
Adding save/restore of HyperLogLog++ calculations in progress gives us the ability to do things like restart a daemon or migrate a computation in progress without losing data.

**Comment by muirmanders** [comment]
For my purposes I have added a more generic []byte marshal and unmarshal interface. I'm wondering: what is the use case for a JSON base64 serialization scheme rather than just a straight binary representation? Would you be receptive to a PR replacing the JSON marshaling with a []byte oriented Marshal()/Unmarshal(), or is it important to keep the JSON marshaling in the API as well?

**Comment by drevell** [comment]
I don't work for Lytics anymore, but FWIW I think adding a more efficient marshalling scheme seems like a good idea. 

If using third-party packages like protobuf, I'd suggest implementing the marshaler in a separate package to avoid outgoing dependencies on non-standard-library packages from the main lytics/hll package.

I don't see any need to remove the existing JSON scheme though, breaking API compatibility makes people sad. Sorry if I've misunderstood, feel free to correct me.

**Comment by araddon** [comment]
Yes, a pr would be welcomed.
